on: push
name: Really cool Reactor demo
jobs:
  push-to-azure:
    name: Publish Azure resources
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az account show
  build-job:
    name: Build .NET project
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - run: dotnet --version
        name: Check .NET version
      - uses: actions/checkout@v3
        name: Checkout code
      - run: |
          dotnet publish \
          --configuration Release \
          --output out
        name: Publish .NET web application
      - uses: actions/upload-artifact@v3
        name: Upload publish output
        with:
          name: web-app
          path: out/
