on: push
name: Really cool Reactor demo
jobs:
  build-job:
    name: Build .NET project
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - run: dotnet --version
        name: Check .NET version
      - uses: actions/checkout@v3
        name: Checkout code
      - run: |
          dotnet publish \
          --configuration Release \
          --output out
        name: Publish .NET web application
